Repository Azure/accelerator-bootstrap-modules, pull requests merged in 2024-09, with the labels that each got.

#32 Bug: Only public networking is allowed with Microsoft-Hosted agents / runners
  alz/azuredevops/locals.tf
  alz/azuredevops/main.tf
  alz/github/locals.tf
  alz/github/main.tf
Labels: PR: Safe to test 🧪

#31 hygeine: Triage policies
  .github/policies/resourceManagement.yml
  .github/workflows/pr-title-check.yml
Labels: Type: Hygiene :broom:

#33 fix: Remove unneeded policies
  .github/policies/resourceManagement.yml
Labels: auto-merge :heavy_check_mark:, Type: Hygiene :broom:

#35 feat: Adding architecture definition module and additional folders variable
  alz/azuredevops/locals.files.tf
  alz/azuredevops/locals.tf
  alz/azuredevops/main.tf
  alz/azuredevops/variables.hidden.tf
  alz/github/locals.files.tf
  alz/github/locals.tf
  alz/github/main.tf
  alz/github/variables.hidden.tf
  alz/local/locals.tf
  alz/local/main.tf
  alz/local/variables.hidden.tf
  modules/files/main.tf
  modules/files/variables.tf
  modules/template_architecture_definition/data.tf
  modules/template_architecture_definition/locals.tf
  modules/template_architecture_definition/outputs.tf
  modules/template_architecture_definition/terraform.tf
  modules/template_architecture_definition/variables.tf
Labels: PR: Safe to test 🧪

#37 feat: Using starter module tfvars for architecture definition inputs
  alz/azuredevops/main.tf
  alz/azuredevops/variables.hidden.tf
  alz/github/main.tf
  alz/github/variables.hidden.tf
  alz/local/main.tf
  alz/local/variables.hidden.tf
  modules/template_architecture_definition/data.tf
  modules/template_architecture_definition/locals.tf
  modules/template_architecture_definition/outputs.tf
  modules/template_architecture_definition/variables.tf
Labels: PR: Safe to test 🧪

#36 fix: Bicep permissions for what-if
  alz/azuredevops/variables.hidden.tf
  alz/github/variables.hidden.tf
  alz/local/variables.hidden.tf
Labels: Type: Bug :beetle:

#39 fix: Add additional permissions for bicep deployment permissions
  alz/azuredevops/variables.hidden.tf
  alz/github/variables.hidden.tf
  alz/local/variables.hidden.tf
Labels: Type: Bug :beetle:

#38 feat: add hubNetworkingMultiRegion validation
  .config/ALZ-Powershell.config.json
Labels: PR: Safe to test 🧪
